### ISSUE TITLE
Current release not compatible with LD server sdk v5

### ISSUE THREAD

**Issue by intel352** [launchdarkly/php-server-sdk-redis-predis#14]
LD server sdk v5 conflicts with predis feature requester, as server sdk defines `$_options` property as array, but the implementation in predis lib doesn't specify `array`. This causes an exception to occur.

The issue is the predis library is currently set to allow any version of LD server sdk <6.0.0, but this should be changed to <5.0.0.

**Comment by keelerm84** [comment]
Thank you for reporting this issue. I will work towards a resolution and let you know once a new update has been released.

**Comment by keelerm84** [comment]
Fixed in 1.2.1.

**Comment by carltondickson** [comment]
I'm using the following combination of packages

```
        "launchdarkly/server-sdk": "4.2.4",
        "launchdarkly/server-sdk-redis-predis": "1.2.1",
```

And trying to configure the SDK to use the Redis feature requester

```
LAUNCH_DARKLY_FEATURE_REQUESTER=\LaunchDarkly\Integrations\Redis::featureRequester
```

I'm still getting the following errors after upgrading (apologies if the upgrade wasn't supposed to fix my issue or I'm configuring the feature requester incorrectly - I'm specifying a feature requester that `is_callable`)

1. \LaunchDarkly\Integrations\Redis::featureRequester, `$options` is type hinted to be `array`

```
LaunchDarkly\Integrations\Redis::featureRequester(): Argument #1 ($options) must be of type array, string given, called in /opt/project/vendor/launchdarkly/server-sdk/src/LaunchDarkly/LDClient.php on line 168
```

2. If I remove the type hint in the above location I get a new error

```
LaunchDarkly\LDClient::getFeatureRequester(): Return value must be of type LaunchDarkly\FeatureRequester, Closure returned
```

Which I can fix by removing the type hinting, similar to what you've done in your tests

**Comment by keelerm84** [comment]
Sorry @carltondickson that you are still experiencing issues. We will work to get this resolved for you.

I'm not entirely clear on exactly how you are saying the SDK is configured. Using the same pinned versions you mentioned, I was able to run the following successfully:

```php
<?php

require 'vendor/autoload.php';

$sdkKey = "your-sdk-key-here";
$featureFlagKey = "your-boolean-flag-key-here";

if (!$sdkKey) {
  echo "*** Please edit index.php to set $sdkKey to your LaunchDarkly SDK key first\n\n";
  exit(1);
}

$fr = LaunchDarkly\Integrations\Redis::featureRequester(["prefix" => "my-key-prefix"]);
$config = [ "feature_requester" => $fr ];
$client = new LaunchDarkly\LDClient($sdkKey, $config);

$user = (new LaunchDarkly\LDUserBuilder("example-user-key"))
    ->name("Sandy")
    ->build();

$flagValue = $client->variation($featureFlagKey, $user, false);
$flagValueStr = $flagValue ? 'true' : 'false';

echo "*** Feature flag '{$featureFlagKey}' is {$flagValueStr} for this context\n\n";
```

Does the above work for you? How does that configuration differ from how you're attempting to use the SDK?
